# Generated by Django 2.0 on 2025-02-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bookId', models.CharField(default='', max_length=255, verbose_name='书籍编号')),
                ('tag', models.CharField(default='', max_length=255, verbose_name='类型')),
                ('title', models.CharField(default='', max_length=255, verbose_name='书名')),
                ('cover', models.CharField(default=0.0, max_length=2555, verbose_name='封面')),
                ('author', models.CharField(default=0, max_length=255, verbose_name='作者')),
                ('press', models.CharField(default='', max_length=255, verbose_name='出版社')),
                ('year', models.CharField(default='', max_length=255, verbose_name='出版年份')),
                ('pageNum', models.CharField(default='', max_length=255, verbose_name='页码')),
                ('price', models.CharField(default='', max_length=255, verbose_name='价格')),
                ('rate', models.CharField(default='', max_length=255, verbose_name='评分')),
                ('starList', models.CharField(default='', max_length=255, verbose_name='星级列表')),
                ('summary', models.TextField(default='', verbose_name='描述')),
                ('detailLink', models.CharField(default='', max_length=255, verbose_name='详情链接')),
                ('createTime', models.CharField(default='', max_length=2555, verbose_name='创建时间')),
                ('comment_len', models.CharField(default='', max_length=255, verbose_name='评论数量')),
                ('commentList', models.TextField(default='', verbose_name='评论列表')),
            ],
            options={
                'db_table': 'booklist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
