# Generated by Django 2.0 on 2025-04-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('behavior_type', models.CharField(choices=[('view', '浏览'), ('rate', '评分'), ('favorite', '收藏'), ('click', '点击')], max_length=20, verbose_name='行为类型')),
                ('rating', models.IntegerField(default=0, verbose_name='评分')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.BookList', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'db_table': 'user_behavior',
            },
        ),
    ]
